"""Router subpackage — core routing logic."""

from ai_router.router.provider import (
    AnthropicProvider,
    ChatMessage,
    CompletionRequest,
    CompletionResponse,
    DeepSeekProvider,
    EmbeddingRequest,
    EmbeddingResponse,
    GoogleProvider,
    ModelCapability,
    ModelInfo,
    OpenAIProvider,
    Provider,
    ProviderType,
    create_provider,
    get_provider_class,
    list_providers,
    register_provider,
)
from ai_router.router.strategy import (
    AdaptiveStrategy,
    LowestCostStrategy,
    LowestLatencyStrategy,
    PerformanceTracker,
    RandomStrategy,
    RouteDecision,
    RouteRequest,
    RouteTarget,
    RoundRobinStrategy,
    SemanticRouter,
    Strategy,
    StrategyType,
    WeightedStrategy,
    create_strategy,
)
from ai_router.router.cache import (
    CacheKeyStrategy,
    CacheManager,
    LRUCache,
    SemanticCache,
)
from ai_router.router.fallback import (
    CircuitBreaker,
    CircuitBreakerConfig,
    FallbackAction,
    FallbackChainEntry,
    FallbackManager,
    FallbackReason,
)
from ai_router.router.metrics import (
    Alert,
    AlertRule,
    AggregatedMetrics,
    MetricType,
    MetricsTracker,
    RequestMetrics,
)
from ai_router.router.rate_limiter import (
    AsyncTokenBucket,
    RateLimit,
    TokenBucket,
    TokenBucketRateLimiter,
    rate_limited,
)

__all__ = [
    # Provider
    "AnthropicProvider",
    "ChatMessage",
    "CompletionRequest",
    "CompletionResponse",
    "DeepSeekProvider",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "GoogleProvider",
    "ModelCapability",
    "ModelInfo",
    "OpenAIProvider",
    "Provider",
    "ProviderType",
    "create_provider",
    "get_provider_class",
    "list_providers",
    "register_provider",
    # Strategy
    "AdaptiveStrategy",
    "LowestCostStrategy",
    "LowestLatencyStrategy",
    "PerformanceTracker",
    "RandomStrategy",
    "RouteDecision",
    "RouteRequest",
    "RouteTarget",
    "RoundRobinStrategy",
    "SemanticRouter",
    "Strategy",
    "StrategyType",
    "WeightedStrategy",
    "create_strategy",
    # Cache
    "CacheKeyStrategy",
    "CacheManager",
    "LRUCache",
    "SemanticCache",
    # Fallback
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "FallbackAction",
    "FallbackChainEntry",
    "FallbackManager",
    "FallbackReason",
    # Metrics
    "Alert",
    "AlertRule",
    "AggregatedMetrics",
    "MetricType",
    "MetricsTracker",
    "RequestMetrics",
    # Rate Limiter
    "AsyncTokenBucket",
    "RateLimit",
    "TokenBucket",
    "TokenBucketRateLimiter",
    "rate_limited",
]
